apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  labels:
    app: hello-world-app
spec:
  selector:
    matchLabels:
        app: hello-world-app
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hello-world-app
    spec:
      containers:
        - name: hello-world-app
          image: 905418152561.dkr.ecr.eu-west-1.amazonaws.com/jenkins-ecr-repo/hello-world:latest
          ports:
            - containerPort: 80
              protocol: TCP
          imagePullPolicy: Always